### ISSUE TITLE
Tracking and Map fusion?

### ISSUE THREAD

**Issue by akashsharma02** [ethz-asl/cblox#38]
Hello,
Was just wondering if there is any plan to open source the tracking related code, (which uses the ORB-SLAM2 tracking and covisibility graph), and the map fusion part of the code? 

In particular, I want to understand how the covariance for the submap-submap pose constraints was calculated for the pose graph optimization.

**Comment by alexmillane** [comment]
I'm not planning on open-sourcing it explicitly at the moment. The reason is that getting the covariance out of ORB-SLAM2 required putting some pretty ugly hacks in the lowest level of the solver. ORB-SLAM2 just isn't built for retrieving that information. With that said, the hacks in question are public on my ORB-SLAM2 fork, see for example this function here:

https://github.com/alexmillane/ORB_SLAM2/blob/master/Thirdparty/g2o/g2o/solvers/cholmod/linear_solver_cholmod.h#L259

We have since moved on from using ORB-SLAM (see [voxgraph](https://github.com/ethz-asl/voxgraph)) so the motivation to clean this up is rather low.

I hope you can find something helpful nevertheless.

**Comment by akashsharma02** [comment]
Thanks, this was helpful.
